### Test server root
GET http://localhost:4000/

//Register
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "FName": "Ellise",
  "LName": "Brown",
  "email": "1234576@mynwu.ac.za",
  "field": "Computer Science",
  "campus": "Mafikeng",
  "password": "Pa$$w0rd"
}

//LOGIN
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email":"1234576@mynwu.ac.za",
  "password": "Pa$$w0rd"
}

//JWT Token from login response
GET http://localhost:4000/api/auth/profile-any
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjEyMzQ1NzZAbXlud3UuYWMuemEiLCJGTmFtZSI6IkVsbGlzZSIsIkxOYW1lIjoiQnJvd24iLCJmaWVsZCI6IkNvbXB1dGVyIFNjaWVuY2UiLCJjYW1wdXMiOiJNYWZpa2VuZyIsImlhdCI6MTc1NzY2NDU5OSwiZXhwIjoxNzU3NjY4MTk5fQ.VEwnLqmYWCzVxQeUCDn-bVkMrX2fcg_RD5YriKF0dbg
